apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: flow-mapper
  human_name: Flow Mapper Component
  type: python3
  version: "3.0"
  logo: "logo.png"
  categories:
    - Processor
  dependencies:
    - pythonPackages.dbfread
    - pythonPackages.pandas
    - pythonPackages.numpy
    - pythonPackages.datar
  inputs:
  - help: DEM file
    human_name: Elevation map
    name: file
    type: file
  - help: rows number
    human_name: Number of rows of file
    name: nrow
    type: integer
  - help: cols number
    human_name: Number of columns of file
    name: ncol
    type: integer
  - help: missing data value
    human_name: Value used for missing data
    name: missing_value
    type: integer
  - help: pit maximum area
    human_name: Maximum area of pit
    name: max_area
    type: integer
  - help: max depth
    human_name: Maximum depth of pit
    name: max_depth
    type: float
  - help: Print messages
    human_name: Verbose
    name: verbose
    type: integer
  - help: rows limits
    human_name: Limits of rows to process
    name: rlim
    type: integer
  - help: cols limits
    human_name: Limits of columns to process
    name: clim
    type: integer
  outputs:
  - help: Directory with outputs
    human_name: Result directory
    name: python_outputs
    type: directory
