apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: form-mapper
  human_name: Form Mapper Component
  type: python3
  version: "3.0"
  logo: "logo.png"
  categories:
    - Processor
  dependencies:
    - pythonPackages.dbfread
    - pythonPackages.pandas
    - pythonPackages.numpy
    - pythonPackages.datar
  inputs:
- help: hyperparameters json file
    human_name: hyperparameters json file
    name: input_jsons
    type: file
  outputs:
  - help: Directory with outputs
    human_name: Result directory
    name: python_outputs
    type: directory
